 server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # Habilita compresión para que la app cargue más rápido
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml
  application/xml application/xml+rss text/javascript;

        location / {
            # Si no encuentra el archivo solicitado, sirve index.html
            try_files $uri $uri/ /index.html;
        }
    }    
